services:
  trading-app:
    build: .
    ports:
      - "3000:3000"   # Flask API
      - "8501:8501"   # Streamlit UI
    environment:
      - FLASK_ENV=production
      - FINNHUB_API_KEY=${FINNHUB_API_KEY:-}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY:-}
      - CURRENCY_LAYER_API_KEY1=${CURRENCY_LAYER_API_KEY1:-}
      - CURRENCY_LAYER_API_KEY2=${CURRENCY_LAYER_API_KEY2:-}
      - CURRENCY_LAYER_API_KEY3=${CURRENCY_LAYER_API_KEY3:-}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - USE_CRAWL4AI=${USE_CRAWL4AI:-true}
      - GOOGLE_SEARCH_API_KEY=${GOOGLE_SEARCH_API_KEY:-}
      - GOOGLE_SEARCH_ENGINE_ID=${GOOGLE_SEARCH_ENGINE_ID:-}
    volumes:
      - ./app/data:/app/app/data
      - ./app/reports:/app/app/reports
      - ./app.log:/app/app.log
    restart: unless-stopped
    command: ["python", "app.py", "both"]