name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Create .env file
      run: |
        cat > .env << EOF
        SECRET_KEY=github_actions_test_key
        WTF_CSRF_SECRET_KEY=github_actions_csrf_key
        FLASK_ENV=production
        DOCKER_ENV=true
        GEMINI_API_KEY=test_key
        USE_CRAWL4AI=false
        EOF
    
    - name: Build Docker images
      run: |
        docker compose build
    
    - name: Test Docker containers
      run: |
        docker compose up -d
        sleep 15
        docker compose ps
        docker compose logs --tail=50
        docker compose down
